name: anytime
description: Anytime Podcast Player

version: 1.1+65

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  audio_service: ^0.18.2
  audio_session: ^0.1.6
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.4
  device_info_plus: ^3.2.0
  extended_image: ^6.0.1
  file_picker: ^4.2.7
  flutter_dialogs: ^2.1.1
  flutter_downloader: 1.7.1
  flutter_html: ^2.2.1
  flutter_launcher_icons: ^0.9.2
  flutter_spinkit: ^5.1.0
  html: ^0.15.0
  just_audio: ^0.9.18
  logging: ^1.0.2
  mp3_info: ^0.2.0
  path_provider: ^2.0.8
  percent_indicator: ^3.4.0
  permission_handler: ^8.3.0
  provider: ^6.0.1
  rxdart: ^0.27.3
  scrollable_positioned_list: ^0.2.3
  sembast: ^3.1.1+1
  share_plus: ^3.0.4
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.17
  xml: ^5.3.1
  flutter_svg: ^0.23.0+1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: e5edaea
  mockito: ^5.0.16
  pedantic: ^1.11.1
  lints: ^1.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/anytime-logo.png"
  image_path_ios: "assets/images/anytime-logo-ios.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png
    - assets/images/anytime-placeholder-logo.png
    - assets/icons/

    # Certificate authorities
    - assets/ca/lets-encrypt-r3.pem

  fonts:
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: JostRegular
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
